languageCode = 'en-gb'
title = 'RhubarbDev'
theme = 'smol'

[params]
    subtitle = "Programming & Procrastination"
    customCSS = ["css/darkmode.css"]

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1

    [[menu.footer]]
        name = "Github"
        url = "https://github.com/RhubarbDev"

